interval: 1h
pod_rules_labels_filled_in:
- name: Check if label app is active on every pod
  labels:
  - app
  filter:
    exclude_namespaces:
    - kube-system
pod_rules_limits_filled_in:
- name: Checks if limits are filled in everywhere
  filter:
    exclude_namespaces:
    - kube-system
pod_rules_requests_filled_in:
- name: Checks if requests are filled in everywhere
  filter:
    exclude_namespaces:
    - kube-system
deployment_rules_replicas_minimum:
- name: Minimum of 2 replicas
  minimum_replicas: 2
email_config:
  enabled: false
  to: test@gmail.com
  from: no-reply@kube-conformity.com
  host: 127.0.0.1
  port: 1025