apiVersion: v1
data:
  config.yaml: |
    interval: 1h
    labels_filled_in_rules:
    - name: Check if label app is active on every pod
      labels:
      - app
      filter:
        namespaces: "!kube-system"
    limits_filled_in_rules:
    - name: Checks if limits are filled in everywhere
      filter:
        namespaces: "!kube-system"
    requests_filled_in_rules:
    - name: Checks if requests are filled in everywhere
kind: ConfigMap
metadata:
  name: kube-conformity