apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-conformity
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-conformity
    spec:
      serviceAccountName: kube-conformity
      containers:
      - name: kube-conformity
        image: sdehaes/kube-conformity:latest
        args:
        - --config-location=/etc/config/config.yaml
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: kube-conformity